### ISSUE TITLE
segmentation fault in turbovisor

### ISSUE THREAD

**Issue by nagadomi** [kernelsauce/turbo#189]
The turbovisor sometimes segfaults when updating a file. 

```
[S 2015/05/07 23:50:11] [web.lua] 200 OK POST /api (127.0.0.1) 3895ms
[d 2015/05/07 23:50:29] Maximum read buffer size reached. Throttling read.
[S 2015/05/07 23:50:33] [web.lua] 200 OK POST /api (127.0.0.1) 3922ms
[I 2015/05/08 04:34:33] [turbovisor.lua] File 'models/scale2.0x_model.t7.back' changed, application restarted!
zsh: segmentation fault (core dumped)  turbovisor web.lua
```
stacktrace is here.
```
Core was generated by `luajit /usr/local/bin/turbovisor web.lua'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  _int_malloc (av=0x7f78485dc760 <main_arena>, bytes=256) at malloc.c:3489
3489	malloc.c: No such file or directory.
(gdb) bt
#0  _int_malloc (av=0x7f78485dc760 <main_arena>, bytes=256) at malloc.c:3489
#1  0x00007f78482a07b0 in __GI___libc_malloc (bytes=256) at malloc.c:2891
#2  0x00007f784828dd18 in _IO_new_popen (command=0x41ad8290 "pgrep -P 18130", mode=0x481436 "r") at iopopen.c:288
#3  0x000000000045ff04 in lj_cf_io_popen ()
#4  0x00000000004770bb in lj_BC_FUNCC ()
#5  0x00000000004656b0 in lua_pcall ()
#6  0x0000000000406b7f in pmain ()
#7  0x00000000004770bb in lj_BC_FUNCC ()
#8  0x000000000046572a in lua_cpcall ()
#9  0x0000000000404b18 in main ()
(gdb) 
```
maybe this line causes a segfault https://github.com/kernelsauce/turbo/blob/1dede97458152a3a3037ae02ecbcd7f1e9662cab/turbovisor.lua#L59, but I don't know why.

**Comment by ddysher** [comment]
Thanks for reporting.  I haven't touched it for a while, but I'll find some time to investigate it.

Is this reproducible?

**Comment by nagadomi** [comment]
I wrote a reproducible example.
https://gist.github.com/nagadomi/9a28d910651b547e1393

### terminal A (run first)
```
$ ruby randomwrite.rb
```
### terminal B
```
$ ulimit -c unlimited
$ turbovisor test.lua 
```
... after a few minutes.
```
[S 2015/05/09 00:41:01] [web.lua] 200 OK GET / (127.0.0.1) 0ms
[I 2015/05/09 00:41:01] [turbovisor.lua] File '8' changed, application restarted!
[S 2015/05/09 00:41:01] [web.lua] 200 OK GET / (127.0.0.1) 0ms
[S 2015/05/09 00:41:01] [web.lua] 200 OK GET / (127.0.0.1) 0ms
[I 2015/05/09 00:41:01] [turbovisor.lua] File '2' changed, application restarted!
[I 2015/05/09 00:41:01] [turbovisor.lua] File '2' changed, application restarted!
[S 2015/05/09 00:41:01] [web.lua] 200 OK GET / (127.0.0.1) 0ms
[S 2015/05/09 00:41:01] [web.lua] 200 OK GET / (127.0.0.1) 0ms
[I 2015/05/09 00:41:01] [turbovisor.lua] File '9' changed, application restarted!
[I 2015/05/09 00:41:01] [turbovisor.lua] File '3' changed, application restarted!
[I 2015/05/09 00:41:01] [turbovisor.lua] File '9' changed, application restarted!
[I 2015/05/09 00:41:01] [turbovisor.lua] File '3' changed, application restarted!
zsh: segmentation fault (core dumped)  turbovisor test.lua
```

**Comment by kernelsauce** [comment]
Thank you for handling this @ddysher. :+1:
